# Generated by Django 3.1.7 on 2021-03-18 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0002_auto_20210318_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.user'),
        ),
    ]
